services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        order: start-first
      placement:
        constraints:
          - node.role == manager
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      LOGIN_RATELIMIT_MAX_BURST: "10"
      LOGIN_RATELIMIT_SECONDS: "60"

      # Swarm secrets exposed as files
      DOMAIN_FILE: /run/secrets/vw_domain_url
      ADMIN_TOKEN_FILE: /run/secrets/vw_admin_token
      SMTP_HOST_FILE: /run/secrets/vw_smtp_host
      SMTP_PORT_FILE: /run/secrets/vw_smtp_port
      SMTP_FROM_FILE: /run/secrets/vw_email
      SMTP_USERNAME_FILE: /run/secrets/vw_email
      SMTP_PASSWORD_FILE: /run/secrets/vw_email_pass
      SMTP_AUTH_MECHANISM: Plain
      SMTP_TIMEOUT: "30"

    volumes:
      - type: bind
        source: /home/bharani/container-data/vaultwarden
        target: /data

    networks: [web]

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/alive"]
      interval: 30s
      timeout: 5s
      retries: 5

    secrets:
      - vw_domain_url
      - vw_admin_token
      - vw_smtp_host
      - vw_smtp_port
      - vw_email
      - vw_email_pass

  vw-backup:
    image: ttionya/vaultwarden-backup:1.25.1
    container_name: vw-backup
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
    environment:
      DATA_DIR: /vaultwarden-data
      BACKUP_KEEP_DAYS: "30"
      RCLONE_REMOTE_NAME: OneDriveSync
      RCLONE_REMOTE_DIR: /VaultwardenBackup/
      CRON: "5 5 * * *"
      ZIP_ENABLE: "TRUE"
      ZIP_PASSWORD_FILE: /run/secrets/zip_pass
      ZIP_TYPE: zip
    volumes:
      - type: bind
        source: /home/bharani/container-data/vaultwarden
        target: /vaultwarden-data
      - type: bind
        source: /home/bharani/container-data/vaultwarden/rclone   # contains rclone/rclone.conf
        target: /config
    networks: [web]
    secrets:
      - source: vw_zip_pass
        target: zip_pass

networks:
  web:
    external: true

secrets:
  vw_domain_url:  { external: true }
  vw_admin_token: { external: true }
  vw_smtp_host:   { external: true }
  vw_smtp_port:   { external: true }
  vw_email:       { external: true }
  vw_email_pass:  { external: true }
  vw_zip_pass:    { external: true }
