tunnel: 53f49069-a8cd-410e-821e-1f2b868cc70f
credentials-file: /etc/cloudflared/53f49069-a8cd-410e-821e-1f2b868cc70f.json

ingress:
  - hostname: portainer.bnitturi.com
    service: http://localhost:9000

  - hostname: vault.bnitturi.com
    path: /safe/bems2304/*
    service: http://vaultwarden:8062

  - hostname: app.gmailit.com
    service: http://localhost:7777
    originRequest:
      httpHostHeader: app.gmailit.com

  - service: http_status:404
