tunnel: 53f49069-a8cd-410e-821e-1f2b868cc70f
credentials-file: /secrets/cloudflared/credentials.json
ingress:
  - hostname: vault.bnitturi.com
    service: http://vaultwarden:80
  - service: http_status:404