  postfix:
    image: private/postfix:latest
    build:
      context: /home/bharani/containers/gmailit/postfix/Dockerfiles
      dockerfile: Dockerfile
    container_name: postfix
    # Postfix on gmailit used .env only for generic vars; we don't need secrets here
    env_file:
      - /home/bharani/containers/gmailit/.env
    environment:
      MAIL_CONFIG: /etc/postfix/conf.d/
    ports:
      # Expose like the old server. If you don't want them public, remove these.
      - "25:25"
      - "587:587"
    volumes:
      # Postfix configs from container-data (read-write to allow lmdb map generation)
      - /home/bharani/container-data/gmailit/postfix/conf.d:/etc/postfix/conf.d:rw

      # ACME certs in container-data (read-only)
      - /home/bharani/container-data/gmailit/acme.sh/conf.d:/etc/acme.sh:ro
    depends_on:
      email:
        condition: service_started
    restart: always
